name: "CI"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libarchive-dev libgoocanvas-2.0-dev valac meson appstream-util xvfb at-spi2-core git gtk-doc-tools build-essential autopoint autoconf libtool sed
    - name: Install unreleased dependencies
      run: |
        git clone https://gitlab.gnome.org/GNOME/goocanvas
        cd goocanvas
        git checkout goocanvas-3.0
        ./autogen.sh
        ./configure --prefix=/usr PYTHON=python3
        sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
        make
        make install
    - name: Build
      # env:
      #   DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install
        xvfb-run -a -s "-screen 0 1024x768x24" \
          dbus-run-session meson test -C build --no-rebuild -v --no-stdsplit --wrap catchsegv
    - name: cleanup xvfb
      run: |
        xvfb_pids=`ps aux | grep tmp/xvfb-run | grep -v grep | awk '{print $2}'`
        if [ "$xvfb_pids" != "" ]; then
          echo "Killing the following xvfb processes: $xvfb_pids"
          sudo kill $xvfb_pids
        else
          echo "No xvfb processes to kill"
        fi
